name: rythm
description: Android Music player written in Dart with Flutter.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.1.0-alpha

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  audiotagger: ^2.2.1
  cupertino_icons: ^1.0.2
  file_picker: ^5.2.4
  flex_color_scheme: ^6.1.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  font_awesome_flutter: ^10.3.0
  hooks_riverpod: ^2.1.3
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  just_audio: ^0.9.31
  just_audio_background: ^0.0.1-beta.9
  marquee: ^2.2.3
  palette_generator: ^0.3.3+2
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  riverpod_annotation: ^1.1.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.0.5

flutter:
  uses-material-design: true

assets:
  - assets/placeholder-image.png
